import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.certificates': 'Certificates',
    'nav.experience': 'Experience',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & Computing Engineer',
    'hero.description': 'Enthusiastic about solving problems obtaining the best results, motivated by new challenges, learning and fast adapting, excellent teamwork skills with multiple stakeholders. Providing customized and helpful support experience, becoming a trusted advisor.',
    'hero.contact': 'Get in Touch',
    'about.title': 'About Me',
    'about.subtitle': 'Systems & computing engineer',
    'about.description': "Systems & computing engineer with deep expertise in database management, data analytics, and full-stack development. Specialized in Python, Java, Elastic, and cloud technologies (Google Cloud, Azure). Strong background in project management, process optimization, and delivering data-driven solutions at scale.",
    'about.interests': 'Passionate about leveraging technology to solve complex problems, optimizing workflows, and mentoring teams. Experience spans from NLP solutions and Elastic implementations to cloud migrations and automated reporting systems.',
    'skills.title': 'Technical Skills',
    'skills.subtitle': 'Character Build & Abilities',
    'skills.frontend': 'Frontend Development',
    'skills.backend': 'Backend Development',
    'skills.database': 'Database & Tools',
    'skills.other': 'Other Skills',
    'projects.title': 'Certificates & Badges',
    'projects.subtitle': 'Collected Achievements & Credentials',
    'projects.cert1.title': 'Elastic Accredited Sales Engineer',
    'projects.cert1.issuer': 'Elastic',
    'projects.cert1.date': '2024',
    'projects.cert1.description': 'Security, Enterprise Search, and Observability professional certification',
    'projects.cert2.title': 'Elastic Accredited Sales Specialist',
    'projects.cert2.issuer': 'Elastic',
    'projects.cert2.date': '2024',
    'projects.cert2.description': 'Specialized in Security, Observability, and Enterprise Search solutions',
    'projects.cert3.title': 'Microsoft Certified: Power BI Data Analyst',
    'projects.cert3.issuer': 'Microsoft',
    'projects.cert3.date': '2023',
    'projects.cert3.description': 'Expert certification in business intelligence and data visualization with Power BI',
    'projects.cert4.title': 'Intro to Large Language Models',
    'projects.cert4.issuer': 'Google Cloud',
    'projects.cert4.date': '2024',
    'projects.cert4.description': 'Foundational knowledge in LLM architecture and applications',
    'projects.cert5.title': 'Intro to Responsible AI',
    'projects.cert5.issuer': 'Google Cloud',
    'projects.cert5.date': '2024',
    'projects.cert5.description': 'Understanding ethical AI development and responsible AI practices',
    'projects.cert6.title': 'Elastic Accredited Sales Professional',
    'projects.cert6.issuer': 'Elastic',
    'projects.cert6.date': '2024',
    'projects.cert6.description': 'Professional accreditation in Elastic Stack solutions and sales engineering',
    'projects.cert7.title': 'Introduction to Generative AI',
    'projects.cert7.issuer': 'Google Cloud',
    'projects.cert7.date': '2024',
    'projects.cert7.description': 'Foundational understanding of generative AI concepts and applications',
    'projects.cert8.title': 'Transformer Models and BERT Model',
    'projects.cert8.issuer': 'Google Cloud',
    'projects.cert8.date': '2024',
    'projects.cert8.description': 'Deep dive into transformer architectures and BERT implementations',
    'projects.cert9.title': 'Encoder-Decoder Architecture',
    'projects.cert9.issuer': 'Google Cloud',
    'projects.cert9.date': '2024',
    'projects.cert9.description': 'Understanding sequence-to-sequence models and encoder-decoder systems',
    'projects.cert10.title': 'Attention Mechanism',
    'projects.cert10.issuer': 'Google Cloud',
    'projects.cert10.date': '2024',
    'projects.cert10.description': 'Mastery of attention mechanisms in neural networks',
    'projects.cert11.title': 'Introduction to Image Generation',
    'projects.cert11.issuer': 'Google Cloud',
    'projects.cert11.date': '2024',
    'projects.cert11.description': 'Fundamentals of AI-powered image generation techniques',
    'projects.cert12.title': 'Create Image Captioning Models',
    'projects.cert12.issuer': 'Google Cloud',
    'projects.cert12.date': '2024',
    'projects.cert12.description': 'Building and deploying image captioning AI models',
    'projects.cert13.title': 'Responsible AI: Applying AI Principles',
    'projects.cert13.issuer': 'Google Cloud',
    'projects.cert13.date': '2024',
    'projects.cert13.description': 'Implementing ethical AI practices in cloud environments',
    'projects.cert14.title': 'Analyze Speech & Language APIs',
    'projects.cert14.issuer': 'Google Cloud',
    'projects.cert14.date': '2024',
    'projects.cert14.description': 'Working with Google Cloud speech and language processing APIs',
    'projects.cert15.title': 'Prepare Data for ML APIs',
    'projects.cert15.issuer': 'Google Cloud',
    'projects.cert15.date': '2024',
    'projects.cert15.description': 'Data preparation and preprocessing for machine learning APIs',
    'projects.cert16.title': 'Google Cloud Big Data & ML Fundamentals',
    'projects.cert16.issuer': 'Google Cloud',
    'projects.cert16.date': '2024',
    'projects.cert16.description': 'Core concepts in big data processing and ML on Google Cloud Platform',
    'projects.cert17.title': 'Azure Fundamentals',
    'projects.cert17.issuer': 'Microsoft',
    'projects.cert17.date': '2023',
    'projects.cert17.description': 'Foundation in Microsoft Azure cloud services and architecture',
    'projects.cert18.title': 'Enterprise Design Thinking Practitioner',
    'projects.cert18.issuer': 'IBM',
    'projects.cert18.date': '2022',
    'projects.cert18.description': 'Applying design thinking methodologies in enterprise contexts',
    'projects.cert19.title': 'Google Project Management Certificate',
    'projects.cert19.issuer': 'Google',
    'projects.cert19.date': '2022',
    'projects.cert19.description': 'Comprehensive project management skills and methodologies',
    'projects.cert20.title': 'Scrum Foundation Professional Certificate',
    'projects.cert20.issuer': 'CertiProf',
    'projects.cert20.date': '2022',
    'projects.cert20.description': 'Certified in Scrum framework and agile methodologies',
    'experience.title': 'Work & Experience',
    'experience.subtitle': 'Quest Log & Achievements Unlocked',
    'experience.senior.title': 'Technical Engineer of Special Projects | Developer & Database Manager',
    'experience.senior.company': 'Enterprise Solutions',
    'experience.senior.period': 'Recent',
    'experience.senior.description': 'Lead development projects, managed diverse SQL and NO-SQL databases, automated data reports (Power BI, Advanced Excel). Optimized report generation from 3-5 hours to 5-10 minutes. Led Python QA automation solutions and implemented Power Automate workflows.',
    'experience.developer.title': 'Data & Analytics Elastic Consultant Engineer',
    'experience.developer.company': 'Elastic Consulting',
    'experience.developer.period': '2023',
    'experience.developer.description': 'Led project planning under Scrum methodology. Developed Python integrations for Elastic with 95%+ analytics metrics. Implemented complex search queries and KNN solutions. Conducted Elastic conferences for 50+ participants. Maintained 90%+ client satisfaction.',
    'experience.intern.title': 'Natural Language Process Consultant Engineer',
    'experience.intern.company': 'NLP Solutions',
    'experience.intern.period': '2022-2023',
    'experience.intern.description': 'Developed NLP-driven software using Python and Java. Implemented Elasticsearch integrations with advanced search features including KNN and cross-reference searches. Full lifecycle development with Jira project management.',
    'experience.pacific.title': 'IT PACIFIC INTERN | Data Quality Manager',
    'experience.pacific.company': 'IT Pacific',
    'experience.pacific.period': '2021-2022',
    'experience.pacific.description': 'Regional data quality management across Colombia, Peru, and Chile. Coached Windows tools courses with 50+ assistants per country. Optimized processes from 5 hours per day to 10 minutes per month using Power Automate. Upgraded overall data quality score to 90% average.',
    'experience.cofounder.title': 'Co-founder | Head Developer',
    'experience.cofounder.company': 'Mobile App Startup',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planned and developed mobile apps with Android Studio (Kotlin). Organized and integrated Firebase-Cloud Firestore DB. Implemented APIs optimizing security and payments collection. Created solutions to unfamiliar problems fulfilling all project expectations.',
    'experience.education.degree': 'Systems & Computing Engineering',
    'experience.education.school': 'Universidad de los Andes',
    'experience.education.period': '2017-2024',
    'experience.education.description': 'Bachelor of Engineering in Systems and Computing. Comprehensive education in software development, database systems, algorithms, data structures, and computer science fundamentals. Focus on data analytics, system architecture, and full-stack development.',
    'contact.title': "Let's Connect",
    'contact.subtitle': 'Feel free to reach out for collaborations or just a friendly chat',
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.skills': 'Habilidades',
    'nav.certificates': 'Certificados',
    'nav.experience': 'Experiencia',
    'nav.contact': 'Contacto',
    'hero.title': 'Ingeniero de Sistemas y Computación',
    'hero.description': 'Entusiasta en resolver problemas obteniendo los mejores resultados, motivado por nuevos desafíos, aprendizaje y adaptación rápida, excelentes habilidades de trabajo en equipo con múltiples stakeholders. Brindando experiencia de soporte personalizada y útil, convirtiéndome en un asesor de confianza.',
    'hero.contact': 'Contáctame',
    'about.subtitle': 'Ingeniero de sistemas y computación',
    'about.description': 'Ingeniero de sistemas y computación con amplia experiencia en gestión de bases de datos, análisis de datos y desarrollo full-stack. Especializado en Python, Java, Elastic y tecnologías cloud (Google Cloud, Azure). Sólida experiencia en gestión de proyectos, optimización de procesos y entrega de soluciones basadas en datos a escala.',
    'about.interests': 'Apasionado por aprovechar la tecnología para resolver problemas complejos, optimizar flujos de trabajo y mentorear equipos. La experiencia abarca desde soluciones NLP e implementaciones Elastic hasta migraciones cloud y sistemas de reportes automatizados.',
    'skills.title': 'Habilidades Técnicas',
    'skills.subtitle': 'Construcción de Personaje y Habilidades',
    'skills.frontend': 'Desarrollo Frontend',
    'skills.backend': 'Desarrollo Backend',
    'skills.database': 'Base de Datos y Herramientas',
    'skills.other': 'Otras Habilidades',
    'projects.title': 'Certificados y Medallas',
    'projects.subtitle': 'Logros y Credenciales Coleccionados',
    'projects.cert1.title': 'Ingeniero de Ventas Acreditado Elastic',
    'projects.cert1.issuer': 'Elastic',
    'projects.cert1.date': '2024',
    'projects.cert1.description': 'Certificación profesional en Seguridad, Enterprise Search y Observabilidad',
    'projects.cert2.title': 'Especialista de Ventas Acreditado Elastic',
    'projects.cert2.issuer': 'Elastic',
    'projects.cert2.date': '2024',
    'projects.cert2.description': 'Especializado en soluciones de Seguridad, Observabilidad y Enterprise Search',
    'projects.cert3.title': 'Certificado Microsoft: Analista de Datos Power BI',
    'projects.cert3.issuer': 'Microsoft',
    'projects.cert3.date': '2023',
    'projects.cert3.description': 'Certificación experta en inteligencia empresarial y visualización de datos con Power BI',
    'projects.cert4.title': 'Introducción a Modelos de Lenguaje Grande',
    'projects.cert4.issuer': 'Google Cloud',
    'projects.cert4.date': '2024',
    'projects.cert4.description': 'Conocimiento fundamental en arquitectura y aplicaciones de LLM',
    'projects.cert5.title': 'Introducción a IA Responsable',
    'projects.cert5.issuer': 'Google Cloud',
    'projects.cert5.date': '2024',
    'projects.cert5.description': 'Comprensión del desarrollo ético de IA y prácticas de IA responsable',
    'projects.cert6.title': 'Profesional de Ventas Acreditado Elastic',
    'projects.cert6.issuer': 'Elastic',
    'projects.cert6.date': '2024',
    'projects.cert6.description': 'Acreditación profesional en soluciones Elastic Stack e ingeniería de ventas',
    'projects.cert7.title': 'Introducción a IA Generativa',
    'projects.cert7.issuer': 'Google Cloud',
    'projects.cert7.date': '2024',
    'projects.cert7.description': 'Comprensión fundamental de conceptos y aplicaciones de IA generativa',
    'projects.cert8.title': 'Modelos Transformer y Modelo BERT',
    'projects.cert8.issuer': 'Google Cloud',
    'projects.cert8.date': '2024',
    'projects.cert8.description': 'Inmersión profunda en arquitecturas transformer e implementaciones BERT',
    'projects.cert9.title': 'Arquitectura Codificador-Decodificador',
    'projects.cert9.issuer': 'Google Cloud',
    'projects.cert9.date': '2024',
    'projects.cert9.description': 'Comprensión de modelos secuencia a secuencia y sistemas codificador-decodificador',
    'projects.cert10.title': 'Mecanismo de Atención',
    'projects.cert10.issuer': 'Google Cloud',
    'projects.cert10.date': '2024',
    'projects.cert10.description': 'Dominio de mecanismos de atención en redes neuronales',
    'projects.cert11.title': 'Introducción a Generación de Imágenes',
    'projects.cert11.issuer': 'Google Cloud',
    'projects.cert11.date': '2024',
    'projects.cert11.description': 'Fundamentos de técnicas de generación de imágenes con IA',
    'projects.cert12.title': 'Crear Modelos de Subtitulado de Imágenes',
    'projects.cert12.issuer': 'Google Cloud',
    'projects.cert12.date': '2024',
    'projects.cert12.description': 'Construcción y despliegue de modelos de IA para subtitulado de imágenes',
    'projects.cert13.title': 'IA Responsable: Aplicando Principios de IA',
    'projects.cert13.issuer': 'Google Cloud',
    'projects.cert13.date': '2024',
    'projects.cert13.description': 'Implementación de prácticas éticas de IA en entornos cloud',
    'projects.cert14.title': 'Analizar APIs de Voz y Lenguaje',
    'projects.cert14.issuer': 'Google Cloud',
    'projects.cert14.date': '2024',
    'projects.cert14.description': 'Trabajo con APIs de procesamiento de voz y lenguaje de Google Cloud',
    'projects.cert15.title': 'Preparar Datos para APIs de ML',
    'projects.cert15.issuer': 'Google Cloud',
    'projects.cert15.date': '2024',
    'projects.cert15.description': 'Preparación y preprocesamiento de datos para APIs de machine learning',
    'projects.cert16.title': 'Fundamentos de Big Data y ML en Google Cloud',
    'projects.cert16.issuer': 'Google Cloud',
    'projects.cert16.date': '2024',
    'projects.cert16.description': 'Conceptos básicos de procesamiento de big data y ML en Google Cloud Platform',
    'projects.cert17.title': 'Fundamentos de Azure',
    'projects.cert17.issuer': 'Microsoft',
    'projects.cert17.date': '2023',
    'projects.cert17.description': 'Fundamentos en servicios y arquitectura cloud de Microsoft Azure',
    'projects.cert18.title': 'Practicante de Design Thinking Empresarial',
    'projects.cert18.issuer': 'IBM',
    'projects.cert18.date': '2022',
    'projects.cert18.description': 'Aplicación de metodologías de design thinking en contextos empresariales',
    'projects.cert19.title': 'Certificado de Gestión de Proyectos de Google',
    'projects.cert19.issuer': 'Google',
    'projects.cert19.date': '2022',
    'projects.cert19.description': 'Habilidades y metodologías integrales de gestión de proyectos',
    'projects.cert20.title': 'Certificado Profesional de Fundamentos Scrum',
    'projects.cert20.issuer': 'CertiProf',
    'projects.cert20.date': '2022',
    'projects.cert20.description': 'Certificado en framework Scrum y metodologías ágiles',
    'experience.title': 'Trabajo y Experiencia',
    'experience.subtitle': 'Registro de Misiones y Logros Desbloqueados',
    'experience.senior.title': 'Ingeniero Técnico de Proyectos Especiales | Desarrollador & Gestor de Bases de Datos',
    'experience.senior.company': 'Enterprise Solutions',
    'experience.senior.period': 'Reciente',
    'experience.senior.description': 'Lideré proyectos de desarrollo, gestioné diversas bases de datos SQL y NO-SQL, automaticé reportes de datos (Power BI, Excel Avanzado). Optimicé generación de reportes de 3-5 horas a 5-10 minutos. Lideré soluciones de automatización QA en Python e implementé flujos de Power Automate.',
    'experience.developer.title': 'Ingeniero Consultor de Datos y Analytics Elastic',
    'experience.developer.company': 'Elastic Consulting',
    'experience.developer.period': '2023',
    'experience.developer.description': 'Lideré planificación de proyectos bajo metodología Scrum. Desarrollé integraciones Python para Elastic con métricas de analytics del 95%+. Implementé búsquedas complejas y soluciones KNN. Realicé conferencias Elastic para 50+ participantes. Mantuve satisfacción del cliente del 90%+.',
    'experience.intern.title': 'Ingeniero Consultor de Procesamiento de Lenguaje Natural',
    'experience.intern.company': 'NLP Solutions',
    'experience.intern.period': '2022-2023',
    'experience.intern.description': 'Desarrollé software basado en NLP usando Python y Java. Implementé integraciones con Elasticsearch con funciones de búsqueda avanzadas incluyendo KNN y búsquedas de referencia cruzada. Desarrollo de ciclo completo con gestión de proyectos en Jira.',
    'experience.pacific.title': 'PASANTE IT PACIFIC | Gestor de Calidad de Datos',
    'experience.pacific.company': 'IT Pacific',
    'experience.pacific.period': '2021-2022',
    'experience.pacific.description': 'Gestión de calidad de datos a nivel regional en Colombia, Perú y Chile. Impartí cursos de herramientas Windows con 50+ asistentes por país. Optimicé procesos de 5 horas por día a 10 minutos por mes usando Power Automate. Mejoré la puntuación de calidad de datos a un promedio del 90%.',
    'experience.cofounder.title': 'Co-fundador | Desarrollador Principal',
    'experience.cofounder.company': 'Startup de Aplicaciones Móviles',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planeé y desarrollé aplicaciones móviles con Android Studio (Kotlin). Organicé e integré Firebase-Cloud Firestore DB. Implementé APIs optimizando seguridad y recolección de pagos. Creé soluciones a problemas no familiares cumpliendo todas las expectativas del proyecto.',
    'experience.education.degree': 'Ingeniería de Sistemas y Computación',
    'experience.education.school': 'Universidad del Norte',
    'experience.education.period': '2017-2023',
    'experience.education.description': 'Título de Ingeniería en Sistemas y Computación. Educación integral en desarrollo de software, sistemas de bases de datos, algoritmos, estructuras de datos y fundamentos de ciencias de la computación. Enfoque en análisis de datos, arquitectura de sistemas y desarrollo full-stack.',
    'contact.title': 'Conectemos',
    'contact.subtitle': 'No dudes en contactarme para colaboraciones o simplemente una charla amistosa',
    'contact.name': 'Tu Nombre',
    'contact.email': 'Tu Correo',
    'contact.message': 'Tu Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
