import { createContext, useContext } from 'react';

export type Language = 'en' | 'es';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.certificates': 'Certificates',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & Computing Engineer · Bilingual · Data, Cloud & AI Specialist',
    'hero.description': 'Bilingual Systems and Computing Engineer with experience in data analytics, database management, automation, cloud services, AI integration, and technical consulting.',
    'hero.contact': 'Get in Touch',
    'hero.availability': 'Available for work',
    'hero.scroll': 'Scroll',
    'about.title': 'About Me',
    'about.subtitle': 'Data, Cloud & AI Specialist',
    'about.description': 'Systems and Computing Engineer experienced in data analytics, database management, automation, cloud services, and technical consulting. Skilled at building scalable solutions, optimizing reporting processes, and delivering measurable business impact with cross-functional teams and clients.',
    'about.interests': 'Experience spans reporting automation, SQL and NoSQL database management, Power BI analytics, NLP solutions, Elastic implementations, cloud migrations, QA automation, and mobile development with Firebase.',
    'about.highlight1.title': 'Data & Analytics',
    'about.highlight1.description': 'From SQL and NoSQL databases to Power BI dashboards — I build reporting and data flows that teams actually rely on to make decisions.',
    'about.highlight2.title': 'Automation & AI',
    'about.highlight2.description': 'I automate repetitive workflows and integrate AI where it adds real value: NLP, LLMs, search, and cloud-based solutions in production.',
    'about.highlight3.title': 'Consulting & Delivery',
    'about.highlight3.description': 'Client-facing experience end to end: scoping, Scrum-based delivery, and clear communication with technical and business stakeholders.',
    'experience.title': 'Work & Experience',
    'experience.subtitle': 'Professional Journey and Academic Background',
    'experience.downloadCV': 'Download CV',
    'experience.senior.title': 'Technical Engineer of Special Projects | Developer & Database Manager',
    'experience.senior.company': 'Mentum Group',
    'experience.senior.period': '2021 - Present',
    'experience.senior.description': 'Lead special development and database initiatives for multiple clients, owning reporting automation, SQL and NoSQL database management, cloud service implementations, project follow-up, stakeholder communication, QA automation planning, Power BI reporting, and Power Automate workflows under Scrum-based delivery.',
    'experience.developer.title': 'Data & Analytics Elastic Consultant Engineer',
    'experience.developer.company': 'NowBit',
    'experience.developer.period': '2022 - 2024',
    'experience.developer.description': 'Led Elastic, analytics, and security-oriented consulting projects, combining project planning, Scrum coordination, Jira administration, client-facing delivery, and technical implementation. Worked on Python integrations for Elastic, analytics and security visibility, SQL-like Elastic queries, search use cases, and internal technical resource optimization.',
    'experience.intern.title': 'Natural Language Process Consultant Engineer',
    'experience.intern.company': 'Avature',
    'experience.intern.period': '2024 - 2025',
    'experience.intern.description': 'Developed and maintained NLP-driven software solutions with Python and Java, collaborating with the NLP team through the full project life cycle and supporting integration of language models, Elasticsearch, KNN search, and cross-reference search capabilities.',
    'experience.pacific.title': 'IT Pacific Intern | Data Quality Manager - Colombia, Peru & Chile',
    'experience.pacific.company': 'Procter & Gamble',
    'experience.pacific.period': '2020 - 2021',
    'experience.pacific.description': 'Analyzed regional data quality, supported client data transfers, improved seller data collection processes, and optimized QA workflows for analytics and feedback applications. Worked with Power Automate, automated emails, alerts, regional monitoring, and Windows tools enablement across Colombia, Peru, and Chile.',
    'experience.cofounder.title': 'Co-Founder / Head of Development',
    'experience.cofounder.company': 'AWKI · Startup',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planned and developed mobile applications, architecture, and cloud functionality using Android Studio, Kotlin, and Firebase Cloud Firestore, including custom integrations for customer needs. Implemented APIs supporting security, user data management, and payment collection while handling development and release-stage issues.',
    'experience.education.ai.degree': 'Artificial Intelligence Development and Applications',
    'experience.education.ai.school': 'Sheridan OT, Canada 🇨🇦',
    'experience.education.ai.period': '2026 - Present',
    'experience.education.ai.description': 'Current studies focused on artificial intelligence development and applied AI solutions.',
    'experience.education.degree': 'Systems & Computing Engineering',
    'experience.education.school': 'Universidad de los Andes · Bogotá, Colombia 🇨🇴',
    'experience.education.period': '2017',
    'experience.education.description':
    ' ',
    'projects.eyebrow': 'Selected Work',
    'projects.title': 'Personal Projects',
    'projects.subtitle': 'A growing collection of products and tools I design and build end to end — exploring ideas from first concept to a shipped experience.',
    'projects.viewProject': 'View project',
    'projects.featured': 'Featured',
    'projects.comingSoon': 'Coming soon',
    'projects.placeholder.description': 'Another project will live here soon — this card is a placeholder ready to be filled in with the next build.',
    'projects.app.type': 'Android app',
    'projects.app.description': 'A personal finance app focused on budget visibility, spending organization, and quick access to the information users need to stay in control.',
    'projects.playStore': 'View on Google Play',
    'projects.feature.budget.title': 'Budget Control',
    'projects.feature.budget.description': 'Designed around simple budget tracking so users can understand how their money is distributed.',
    'projects.feature.insights.title': 'Financial Overview',
    'projects.feature.insights.description': 'A visual layout for reviewing income, expenses, and spending behavior without adding friction.',
    'projects.feature.workflow.title': 'Daily Use Flow',
    'projects.feature.workflow.description': 'Focused on practical mobile interactions for checking balances, categories, and recurring personal finance tasks.',
    'projects.gallery.hint': 'Swipe to explore the app',
    'projects.mockup.balanceLabel': 'Balance',
    'projects.mockup.income': 'Income',
    'projects.mockup.expenses': 'Expenses',
    'projects.mockup.item.food': 'Food',
    'projects.mockup.item.transport': 'Transit',
    'projects.mockup.item.savings': 'Savings',
    'contact.title': "Let's Connect",
    'contact.subtitle': 'Feel free to reach out for collaborations or just a friendly chat',
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.emailCard': "Send me an email and I'll get back to you as soon as possible",
    'contact.linkedinCard': 'Connect with me on LinkedIn for professional networking',
    'contact.cvCard': 'Download my CV to learn more about my experience and skills',
    'contact.viewProfile': 'View Profile',
    'contact.downloadCV': 'Download CV',
    'contact.bottomCta': 'You made it this far. We should probably work together.',
    'skills.title': 'Technical Skills',
    'skills.subtitle': 'The stack and tools I work with — and how deep I go in each',
    'skills.level': 'Proficiency',
    'skills.stats.areas': 'Focus areas',
    'skills.stats.skills': 'Skills',
    'skills.stats.years': 'Years of experience',
    'certificates.title': 'Certificates & Badges',
    'certificates.subtitle': 'Certifications, accreditations, and professional training',
    'certificates.type.certification': 'Certification',
    'certificates.type.accreditation': 'Accreditation',
    'certificates.type.training': 'Course / Training',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.skills': 'Habilidades',
    'nav.certificates': 'Certificados',
    'nav.experience': 'Experiencia',
    'nav.projects': 'Proyectos',
    'nav.contact': 'Contacto',
    'hero.title': 'Ingeniero de Sistemas y Computación · Bilingüe · Especialista en Datos, Cloud e IA',
    'hero.description': 'Ingeniero de Sistemas y Computación bilingüe con experiencia en analítica de datos, gestión de bases de datos, automatización, servicios cloud, integración de IA y consultoría técnica.',
    'hero.contact': 'Contáctame',
    'hero.availability': 'Disponible para proyectos',
    'hero.scroll': 'Desliza',
    'about.title': 'Sobre Mi',
    'about.subtitle': 'Especialista en Datos, Cloud e IA',
    'about.description': 'Ingeniero de Sistemas y Computación con experiencia en analítica de datos, gestión de bases de datos, automatización, servicios cloud y consultoría técnica. Hábil desarrollando soluciones escalables, optimizando procesos de reportería y trabajando con equipos multifuncionales y clientes para entregar impacto medible.',
    'about.interests': 'La experiencia abarca automatización de reportes, gestión de bases SQL y NoSQL, analítica con Power BI, soluciones NLP, implementaciones Elastic, migraciones cloud, automatización QA y desarrollo móvil con Firebase.',
    'about.highlight1.title': 'Datos y Analítica',
    'about.highlight1.description': 'De bases de datos SQL y NoSQL a dashboards en Power BI — construyo reportería y flujos de datos en los que los equipos realmente confían para decidir.',
    'about.highlight2.title': 'Automatización e IA',
    'about.highlight2.description': 'Automatizo flujos repetitivos e integro IA donde aporta valor real: NLP, LLMs, búsqueda y soluciones cloud en producción.',
    'about.highlight3.title': 'Consultoría y Entrega',
    'about.highlight3.description': 'Experiencia de cara al cliente de principio a fin: alcance, entregas bajo Scrum y comunicación clara con perfiles técnicos y de negocio.',
    'experience.title': 'Trabajo y Experiencia',
    'experience.subtitle': 'Trayectoria Profesional y Formación Académica',
    'experience.downloadCV': 'Descargar CV',
    'experience.senior.title': 'Ingeniero Técnico de Proyectos Especiales | Desarrollador & Gestor de Bases de Datos',
    'experience.senior.company': 'Mentum Group',
    'experience.senior.period': '2021 - Presente',
    'experience.senior.description': 'Lidero iniciativas especiales de desarrollo y bases de datos para múltiples clientes, incluyendo automatización de reportes, gestión de bases SQL y NoSQL, implementaciones cloud, seguimiento de proyectos, comunicación con stakeholders, planeación de automatización QA, reportería en Power BI y flujos de Power Automate bajo entregas basadas en Scrum.',
    'experience.developer.title': 'Ingeniero Consultor de Datos y Analytics Elastic',
    'experience.developer.company': 'NowBit',
    'experience.developer.period': '2022 - 2024',
    'experience.developer.description': 'Lideré proyectos de consultoría en Elastic, analítica y seguridad, combinando planeación de proyectos, coordinación Scrum, administración de Jira, entrega frente a cliente e implementación técnica. Trabajé en integraciones Python para Elastic, visibilidad de analítica y seguridad, consultas Elastic tipo SQL, casos de búsqueda y optimización de recursos técnicos internos.',
    'experience.intern.title': 'Ingeniero Consultor de Procesamiento de Lenguaje Natural',
    'experience.intern.company': 'Avature',
    'experience.intern.period': '2024 - 2025',
    'experience.intern.description': 'Desarrollé y mantuve soluciones de software impulsadas por NLP con Python y Java, colaborando con el equipo NLP durante todo el ciclo de vida del proyecto y apoyando la integración de modelos de lenguaje, Elasticsearch, búsqueda KNN y capacidades de búsqueda por referencia cruzada.',
    'experience.pacific.title': 'Pasante IT Pacific | Gestor de Calidad de Datos - Colombia, Perú y Chile',
    'experience.pacific.company': 'Procter & Gamble',
    'experience.pacific.period': '2020 - 2021',
    'experience.pacific.description': 'Analicé calidad de datos regional, apoyé transferencias de datos de clientes, mejoré procesos de recolección de datos de vendedores y optimicé flujos QA para aplicaciones de analítica y feedback. Trabajé con Power Automate, correos automatizados, alertas, monitoreo regional y habilitación en herramientas Windows para Colombia, Perú y Chile.',
    'experience.cofounder.title': 'Co-Fundador / Head of Development',
    'experience.cofounder.company': 'AWKI · Startup',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planeé y desarrollé aplicaciones móviles, arquitectura y funcionalidad cloud usando Android Studio, Kotlin y Firebase Cloud Firestore, incluyendo integraciones personalizadas para necesidades de clientes. Implementé APIs de seguridad, gestión de datos de usuario y recaudo de pagos, y manejé problemas de desarrollo y lanzamiento.',
    'experience.education.ai.degree': 'Desarrollo y Aplicaciones de Inteligencia Artificial',
    'experience.education.ai.school': 'Sheridan OT, Canadá 🇨🇦',
    'experience.education.ai.period': '2026 - Presente',
    'experience.education.ai.description': 'Formación actual enfocada en desarrollo de inteligencia artificial y soluciones aplicadas de IA.',
    'experience.education.degree': 'Ingeniería de Sistemas y Computación',
    'experience.education.school': 'Universidad de los Andes · Bogotá, Colombia 🇨🇴',
    'experience.education.period': '2017',
    'experience.education.description':
    ' ',
    'projects.eyebrow': 'Trabajo Seleccionado',
    'projects.title': 'Proyectos Personales',
    'projects.subtitle': 'Una colección en crecimiento de productos y herramientas que diseño y desarrollo de principio a fin — explorando ideas desde el concepto hasta una experiencia lista para usar.',
    'projects.viewProject': 'Ver proyecto',
    'projects.featured': 'Destacado',
    'projects.comingSoon': 'Próximamente',
    'projects.placeholder.description': 'Pronto vivirá aquí otro proyecto — esta tarjeta es un marcador listo para completar con el siguiente desarrollo.',
    'projects.app.type': 'App Android',
    'projects.app.description': 'Una app de finanzas personales enfocada en visibilidad de presupuesto, organización de gastos y acceso rápido a la información que el usuario necesita para mantener el control.',
    'projects.playStore': 'Ver en Google Play',
    'projects.feature.budget.title': 'Control de Presupuesto',
    'projects.feature.budget.description': 'Diseñada alrededor de seguimiento simple de presupuesto para entender cómo se distribuye el dinero.',
    'projects.feature.insights.title': 'Resumen Financiero',
    'projects.feature.insights.description': 'Un diseño visual para revisar ingresos, gastos y comportamiento financiero sin agregar fricción.',
    'projects.feature.workflow.title': 'Flujo de Uso Diario',
    'projects.feature.workflow.description': 'Enfocada en interacciones móviles prácticas para revisar balances, categorías y tareas recurrentes de finanzas personales.',
    'projects.gallery.hint': 'Desliza para explorar la app',
    'projects.mockup.balanceLabel': 'Balance',
    'projects.mockup.income': 'Ingresos',
    'projects.mockup.expenses': 'Gastos',
    'projects.mockup.item.food': 'Comida',
    'projects.mockup.item.transport': 'Transporte',
    'projects.mockup.item.savings': 'Ahorro',
    'contact.title': 'Conectemos',
    'contact.subtitle': 'No dudes en contactarme para colaboraciones o simplemente una charla amistosa',
    'contact.name': 'Tu Nombre',
    'contact.email': 'Tu Correo',
    'contact.message': 'Tu Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.emailCard': 'Envíame un correo y te responderé lo antes posible',
    'contact.linkedinCard': 'Conéctate conmigo en LinkedIn para networking profesional',
    'contact.cvCard': 'Descarga mi CV para conocer más sobre mi experiencia y habilidades',
    'contact.viewProfile': 'Ver Perfil',
    'contact.downloadCV': 'Descargar CV',
    'contact.bottomCta': 'Llegaste hasta aquí. Probablemente deberíamos trabajar juntos.',
    'skills.title': 'Habilidades Técnicas',
    'skills.subtitle': 'El stack y las herramientas con las que trabajo — y mi nivel en cada una',
    'skills.level': 'Nivel de dominio',
    'skills.stats.areas': 'Áreas de enfoque',
    'skills.stats.skills': 'Habilidades',
    'skills.stats.years': 'Años de experiencia',
    'certificates.title': 'Certificados e Insignias',
    'certificates.subtitle': 'Certificaciones, acreditaciones y formación profesional',
    'certificates.type.certification': 'Certificación',
    'certificates.type.accreditation': 'Acreditación',
    'certificates.type.training': 'Curso / Formación',
  },
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
