import { createContext, useContext } from 'react';

export type Language = 'en' | 'es';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.certificates': 'Certificates',
    'nav.experience': 'Experience',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'hero.title': 'Systems & Computing Engineer',
    'hero.description': 'Enthusiastic about solving problems obtaining the best results, motivated by new challenges, learning and fast adapting, excellent teamwork skills with multiple stakeholders. Providing customized and helpful support experience, becoming a trusted advisor.',
    'hero.contact': 'Get in Touch',
    'hero.availability': 'Available for work',
    'hero.scroll': 'Scroll',
    'about.title': 'About Me',
    'about.subtitle': 'Systems & computing engineer',
    'about.description': "Systems & computing engineer with deep expertise in database management, data analytics, and full-stack development. Specialized in Python, Java, Elastic, and cloud technologies (Google Cloud, Azure). Strong background in project management, process optimization, and delivering data-driven solutions at scale.",
    'about.interests': 'Passionate about leveraging technology to solve complex problems, optimizing workflows, and mentoring teams. Experience spans from NLP solutions and Elastic implementations to cloud migrations and automated reporting systems.',
    'experience.title': 'Work & Experience',
    'experience.subtitle': 'Professional Journey and Academic Background',
    'experience.downloadCV': 'Download CV',
    'experience.senior.title': 'Technical Engineer of Special Projects | Developer & Database Manager',
    'experience.senior.company': 'Enterprise Solutions',
    'experience.senior.period': 'Recent',
    'experience.senior.description': 'Lead development projects, managed diverse SQL and NO-SQL databases, automated data reports (Power BI, Advanced Excel). Optimized report generation from 3-5 hours to 5-10 minutes. Led Python QA automation solutions and implemented Power Automate workflows.',
    'experience.developer.title': 'Data & Analytics Elastic Consultant Engineer',
    'experience.developer.company': 'Elastic Consulting',
    'experience.developer.period': '2023',
    'experience.developer.description': 'Led project planning under Scrum methodology. Developed Python integrations for Elastic with 95%+ analytics metrics. Implemented complex search queries and KNN solutions. Conducted Elastic conferences for 50+ participants. Maintained 90%+ client satisfaction.',
    'experience.intern.title': 'Natural Language Process Consultant Engineer',
    'experience.intern.company': 'NLP Solutions',
    'experience.intern.period': '2022-2023',
    'experience.intern.description': 'Developed NLP-driven software using Python and Java. Implemented Elasticsearch integrations with advanced search features including KNN and cross-reference searches. Full lifecycle development with Jira project management.',
    'experience.pacific.title': 'IT PACIFIC INTERN | Data Quality Manager',
    'experience.pacific.company': 'IT Pacific',
    'experience.pacific.period': '2021-2022',
    'experience.pacific.description': 'Regional data quality management across Colombia, Peru, and Chile. Coached Windows tools courses with 50+ assistants per country. Optimized processes from 5 hours per day to 10 minutes per month using Power Automate. Upgraded overall data quality score to 90% average.',
    'experience.cofounder.title': 'Co-founder | Head Developer',
    'experience.cofounder.company': 'Mobile App Startup',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planned and developed mobile apps with Android Studio (Kotlin). Organized and integrated Firebase-Cloud Firestore DB. Implemented APIs optimizing security and payments collection. Created solutions to unfamiliar problems fulfilling all project expectations.',
    'experience.education.degree': 'Systems & Computing Engineering (Computer Science)',
    'experience.education.school': 'Universidad de los Andes',
    'experience.education.period': '2017–2024',
    'experience.education.description':
    ' ',
    'projects.eyebrow': 'Selected Work',
    'projects.title': 'Personal Projects',
    'projects.subtitle': 'A growing collection of products and tools I design and build end to end — exploring ideas from first concept to a shipped experience.',
    'projects.viewProject': 'View project',
    'projects.featured': 'Featured',
    'projects.comingSoon': 'Coming soon',
    'projects.placeholder.description': 'Another project will live here soon — this card is a placeholder ready to be filled in with the next build.',
    'projects.app.type': 'Android app',
    'projects.app.description': 'A personal finance app focused on budget visibility, spending organization, and quick access to the information users need to stay in control.',
    'projects.playStore': 'View on Google Play',
    'projects.feature.budget.title': 'Budget Control',
    'projects.feature.budget.description': 'Designed around simple budget tracking so users can understand how their money is distributed.',
    'projects.feature.insights.title': 'Financial Overview',
    'projects.feature.insights.description': 'A visual layout for reviewing income, expenses, and spending behavior without adding friction.',
    'projects.feature.workflow.title': 'Daily Use Flow',
    'projects.feature.workflow.description': 'Focused on practical mobile interactions for checking balances, categories, and recurring personal finance tasks.',
    'projects.gallery.hint': 'Swipe to explore the app',
    'projects.mockup.balanceLabel': 'Balance',
    'projects.mockup.income': 'Income',
    'projects.mockup.expenses': 'Expenses',
    'projects.mockup.item.food': 'Food',
    'projects.mockup.item.transport': 'Transit',
    'projects.mockup.item.savings': 'Savings',
    'contact.title': "Let's Connect",
    'contact.subtitle': 'Feel free to reach out for collaborations or just a friendly chat',
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.emailCard': "Send me an email and I'll get back to you as soon as possible",
    'contact.linkedinCard': 'Connect with me on LinkedIn for professional networking',
    'contact.cvCard': 'Download my CV to learn more about my experience and skills',
    'contact.viewProfile': 'View Profile',
    'contact.downloadCV': 'Download CV',
    'contact.bottomCta': 'You made it this far. We should probably work together.',
    'skills.title': 'Technical Skills',
    'skills.subtitle': 'Character Build & Abilities',
    'certificates.title': 'Certificates & Badges',
    'certificates.subtitle': 'Collected Achievements & Credentials',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.skills': 'Habilidades',
    'nav.certificates': 'Certificados',
    'nav.experience': 'Experiencia',
    'nav.projects': 'Proyectos',
    'nav.contact': 'Contacto',
    'hero.title': 'Ingeniero de Sistemas y Computación',
    'hero.description': 'Entusiasta en resolver problemas obteniendo los mejores resultados, motivado por nuevos desafíos, aprendizaje y adaptación rápida, excelentes habilidades de trabajo en equipo con múltiples stakeholders. Brindando experiencia de soporte personalizada y útil, convirtiéndome en un asesor de confianza.',
    'hero.contact': 'Contáctame',
    'hero.availability': 'Disponible para proyectos',
    'hero.scroll': 'Desliza',
    'about.title': 'Sobre Mi',
    'about.subtitle': 'Ingeniero de sistemas y computación',
    'about.description': 'Ingeniero de sistemas y computación con amplia experiencia en gestión de bases de datos, análisis de datos y desarrollo full-stack. Especializado en Python, Java, Elastic y tecnologías cloud (Google Cloud, Azure). Sólida experiencia en gestión de proyectos, optimización de procesos y entrega de soluciones basadas en datos a escala.',
    'about.interests': 'Apasionado por aprovechar la tecnología para resolver problemas complejos, optimizar flujos de trabajo y mentorear equipos. La experiencia abarca desde soluciones NLP e implementaciones Elastic hasta migraciones cloud y sistemas de reportes automatizados.',
    'experience.title': 'Trabajo y Experiencia',
    'experience.subtitle': 'Trayectoria Profesional y Formación Académica',
    'experience.downloadCV': 'Descargar CV',
    'experience.senior.title': 'Ingeniero Técnico de Proyectos Especiales | Desarrollador & Gestor de Bases de Datos',
    'experience.senior.company': 'Enterprise Solutions',
    'experience.senior.period': 'Reciente',
    'experience.senior.description': 'Lideré proyectos de desarrollo, gestioné diversas bases de datos SQL y NO-SQL, automaticé reportes de datos (Power BI, Excel Avanzado). Optimicé generación de reportes de 3-5 horas a 5-10 minutos. Lideré soluciones de automatización QA en Python e implementé flujos de Power Automate.',
    'experience.developer.title': 'Ingeniero Consultor de Datos y Analytics Elastic',
    'experience.developer.company': 'Elastic Consulting',
    'experience.developer.period': '2023',
    'experience.developer.description': 'Lideré planificación de proyectos bajo metodología Scrum. Desarrollé integraciones Python para Elastic con métricas de analytics del 95%+. Implementé búsquedas complejas y soluciones KNN. Realicé conferencias Elastic para 50+ participantes. Mantuve satisfacción del cliente del 90%+.',
    'experience.intern.title': 'Ingeniero Consultor de Procesamiento de Lenguaje Natural',
    'experience.intern.company': 'NLP Solutions',
    'experience.intern.period': '2022-2023',
    'experience.intern.description': 'Desarrollé software basado en NLP usando Python y Java. Implementé integraciones con Elasticsearch con funciones de búsqueda avanzadas incluyendo KNN y búsquedas de referencia cruzada. Desarrollo de ciclo completo con gestión de proyectos en Jira.',
    'experience.pacific.title': 'PASANTE IT PACIFIC | Gestor de Calidad de Datos',
    'experience.pacific.company': 'IT Pacific',
    'experience.pacific.period': '2021-2022',
    'experience.pacific.description': 'Gestión de calidad de datos a nivel regional en Colombia, Perú y Chile. Impartí cursos de herramientas Windows con 50+ asistentes por país. Optimicé procesos de 5 horas por día a 10 minutos por mes usando Power Automate. Mejoré la puntuación de calidad de datos a un promedio del 90%.',
    'experience.cofounder.title': 'Co-fundador | Desarrollador Principal',
    'experience.cofounder.company': 'Startup de Aplicaciones Móviles',
    'experience.cofounder.period': '2020-2021',
    'experience.cofounder.description': 'Planeé y desarrollé aplicaciones móviles con Android Studio (Kotlin). Organicé e integré Firebase-Cloud Firestore DB. Implementé APIs optimizando seguridad y recolección de pagos. Creé soluciones a problemas no familiares cumpliendo todas las expectativas del proyecto.',
    'experience.education.degree': 'Ingeniería de Sistemas y Computación',
    'experience.education.school': 'Universidad de los Andes',
    'experience.education.period': '2017–2024',
    'experience.education.description':
    ' ',
    'projects.eyebrow': 'Trabajo Seleccionado',
    'projects.title': 'Proyectos Personales',
    'projects.subtitle': 'Una colección en crecimiento de productos y herramientas que diseño y desarrollo de principio a fin — explorando ideas desde el concepto hasta una experiencia lista para usar.',
    'projects.viewProject': 'Ver proyecto',
    'projects.featured': 'Destacado',
    'projects.comingSoon': 'Próximamente',
    'projects.placeholder.description': 'Pronto vivirá aquí otro proyecto — esta tarjeta es un marcador listo para completar con el siguiente desarrollo.',
    'projects.app.type': 'App Android',
    'projects.app.description': 'Una app de finanzas personales enfocada en visibilidad de presupuesto, organización de gastos y acceso rápido a la información que el usuario necesita para mantener el control.',
    'projects.playStore': 'Ver en Google Play',
    'projects.feature.budget.title': 'Control de Presupuesto',
    'projects.feature.budget.description': 'Diseñada alrededor de seguimiento simple de presupuesto para entender cómo se distribuye el dinero.',
    'projects.feature.insights.title': 'Resumen Financiero',
    'projects.feature.insights.description': 'Un diseño visual para revisar ingresos, gastos y comportamiento financiero sin agregar fricción.',
    'projects.feature.workflow.title': 'Flujo de Uso Diario',
    'projects.feature.workflow.description': 'Enfocada en interacciones móviles prácticas para revisar balances, categorías y tareas recurrentes de finanzas personales.',
    'projects.gallery.hint': 'Desliza para explorar la app',
    'projects.mockup.balanceLabel': 'Balance',
    'projects.mockup.income': 'Ingresos',
    'projects.mockup.expenses': 'Gastos',
    'projects.mockup.item.food': 'Comida',
    'projects.mockup.item.transport': 'Transporte',
    'projects.mockup.item.savings': 'Ahorro',
    'contact.title': 'Conectemos',
    'contact.subtitle': 'No dudes en contactarme para colaboraciones o simplemente una charla amistosa',
    'contact.name': 'Tu Nombre',
    'contact.email': 'Tu Correo',
    'contact.message': 'Tu Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.emailCard': 'Envíame un correo y te responderé lo antes posible',
    'contact.linkedinCard': 'Conéctate conmigo en LinkedIn para networking profesional',
    'contact.cvCard': 'Descarga mi CV para conocer más sobre mi experiencia y habilidades',
    'contact.viewProfile': 'Ver Perfil',
    'contact.downloadCV': 'Descargar CV',
    'contact.bottomCta': 'Llegaste hasta aquí. Probablemente deberíamos trabajar juntos.',
    'skills.title': 'Habilidades Técnicas',
    'skills.subtitle': 'Construcción de Personaje y Habilidades',
    'certificates.title': 'Certificados e Insignias',
    'certificates.subtitle': 'Logros y Credenciales Obtenidos',
  },
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
